import pytest

from gerbera_sdk import Connection
from gerbera_sdk.contracts.command_contract import ParameterType
from gerbera_sdk.contracts.firmware_contract import ColumnType, PinMode
from gerbera_sdk.firmware.configurations import DEVICES_MAPPING
from gerbera_sdk.firmware.devices.dcmotor import DCMotorFirmwareBuilder
from gerbera_sdk.firmware.devices.hcsr04 import HCSR04FirmwareBuilder
from gerbera_sdk.firmware.devices.hw201 import HW201FirmwareBuilder
from gerbera_sdk.firmware.devices.led import LEDFirmwareBuilder
from gerbera_sdk.firmware.devices.mg996r import MG996RFirmwareBuilder
from gerbera_sdk.firmware.devices.sg90 import SG90FirmwareBuilder


def connection(
    component_type: str,
    pins: dict[str, str],
    database=None,
    name: str | None = None,
) -> Connection:
    return Connection(
        id=f"{component_type}-1",
        microcontroller_id="board-1",
        name=name or component_type,
        component_type=component_type,
        pins=pins,
        database=database,
    )


def test_all_supported_components_are_registered() -> None:
    assert DEVICES_MAPPING["hw201"] is HW201FirmwareBuilder
    assert DEVICES_MAPPING["hcsr04"] is HCSR04FirmwareBuilder
    assert DEVICES_MAPPING["led"] is LEDFirmwareBuilder
    assert DEVICES_MAPPING["sg90"] is SG90FirmwareBuilder
    assert DEVICES_MAPPING["mg996r"] is MG996RFirmwareBuilder
    assert DEVICES_MAPPING["dcmotor"] is DCMotorFirmwareBuilder


def test_hw201_read_contract_without_database() -> None:
    builder = HW201FirmwareBuilder()
    conn = connection("hw201", {"out": "7"}, name="obstacle_sensor")

    assert [(pin.pin, pin.mode) for pin in builder.pin_modes(conn)] == [
        ("7", PinMode.INPUT)
    ]
    assert [command.method for command in builder.required_commands(conn)] == ["READ"]
    assert builder.required_schema(conn)["value"].type == ColumnType.INTEGER
    assert builder.build_definitions(conn) == ""
    assert builder.build_stream_lines(conn) == []

    handler = builder.build_handler(conn)
    assert "digitalRead(7)" in handler
    assert "MCP,hw201_hw201-1,value:" in handler
    assert 'if (action == "WRITE")' not in handler


def test_hw201_stream_contract_with_database() -> None:
    builder = HW201FirmwareBuilder()
    conn = connection("hw201", {"out": "7"}, database=object(), name="obstacle_sensor")

    commands = builder.required_commands(conn)
    schema = builder.required_schema(conn)
    handler = builder.build_handler(conn)
    stream_lines = "\n".join(builder.build_stream_lines(conn))

    assert [command.method for command in commands] == ["READ", "WRITE"]
    assert commands[1].params["state"].enum == ["on", "off"]
    assert schema["id"].primary_key is True
    assert schema["id"].sql_suffix == "GENERATED BY DEFAULT AS IDENTITY"
    assert schema["created_at"].default == "CURRENT_TIMESTAMP"
    assert "bool obstacle_sensor_stream_on = false;" in builder.build_definitions(conn)
    assert "STREAM,hw201_hw201-1,value:" in stream_lines
    assert "obstacle_sensor_stream_on = true;" in handler
    assert "obstacle_sensor_stream_on = false;" in handler


def test_led_write_contract() -> None:
    builder = LEDFirmwareBuilder()
    conn = connection("led", {"out": "13"}, name="green_led")

    commands = builder.required_commands(conn)
    handler = builder.build_handler(conn)

    assert [(pin.pin, pin.mode) for pin in builder.pin_modes(conn)] == [
        ("13", PinMode.OUTPUT)
    ]
    assert [command.method for command in commands] == ["WRITE"]
    assert commands[0].params["state"].type == ParameterType.STRING
    assert commands[0].params["state"].enum == ["on", "off"]
    assert "digitalWrite(13, HIGH);" in handler
    assert "digitalWrite(13, LOW);" in handler
    assert "error:invalid_value" in handler


def test_sg90_servo_contract() -> None:
    builder = SG90FirmwareBuilder()
    conn = connection("sg90", {"signal": "10"}, name="servo_motor")

    libraries = builder.required_libraries()
    commands = builder.required_commands(conn)

    assert libraries[0].include == "Servo.h"
    assert libraries[0].install == "Servo"
    assert builder.pin_modes(conn) == []
    assert commands[0].method == "WRITE"
    assert commands[0].params["angle"].type == ParameterType.INT
    assert commands[0].params["angle"].min == 0
    assert commands[0].params["angle"].max == 180
    assert "Servo servo_motor_servo;" in builder.build_definitions(conn)
    assert builder.build_setup_lines(conn) == ["  servo_motor_servo.attach(10);"]
    assert "servo_motor_servo.write(angle);" in builder.build_handler(conn)


def test_mg996r_reuses_servo_contract_with_distinct_template() -> None:
    builder = MG996RFirmwareBuilder()
    conn = connection("mg996r", {"signal": "10"}, name="heavy_servo")

    assert builder.template_name == "mg996r_write"
    assert builder.required_commands(conn)[0].params["angle"].max == 180
    assert "Servo heavy_servo_servo;" in builder.build_definitions(conn)
    assert "heavy_servo_servo.write(angle);" in builder.build_handler(conn)


def test_hcsr04_read_contract_without_database() -> None:
    builder = HCSR04FirmwareBuilder()
    conn = connection("hcsr04", {"trig": "8", "echo": "9"}, name="distance_sensor")

    assert [(pin.pin, pin.mode) for pin in builder.pin_modes(conn)] == [
        ("8", PinMode.OUTPUT),
        ("9", PinMode.INPUT),
    ]
    assert [command.method for command in builder.required_commands(conn)] == ["READ"]
    assert builder.build_definitions(conn) == ""
    assert builder.build_stream_lines(conn) == []

    handler = builder.build_handler(conn)
    assert "pulseIn(9, HIGH, 30000)" in handler
    assert "MCP,hcsr04_hcsr04-1,distance_cm:" in handler
    assert "error:timeout" in handler


def test_hcsr04_stream_contract_with_database() -> None:
    builder = HCSR04FirmwareBuilder()
    conn = connection(
        "hcsr04",
        {"trig": "8", "echo": "9"},
        database=object(),
        name="distance_sensor",
    )

    commands = builder.required_commands(conn)
    schema = builder.required_schema(conn)
    stream_lines = "\n".join(builder.build_stream_lines(conn))
    handler = builder.build_handler(conn)

    assert [command.method for command in commands] == ["READ", "WRITE"]
    assert commands[1].params["state"].enum == ["on", "off"]
    assert schema["distance_cm"].type == ColumnType.FLOAT
    assert schema["created_at"].default == "CURRENT_TIMESTAMP"
    assert "bool distance_sensor_stream_on = false;" in builder.build_definitions(conn)
    assert "STREAM,hcsr04_hcsr04-1,distance_cm:" in stream_lines
    assert "distance_sensor_stream_on = true;" in handler
    assert "distance_sensor_stream_on = false;" in handler


def test_dcmotor_write_contract_requires_pwm_enable_pin() -> None:
    builder = DCMotorFirmwareBuilder()
    conn = connection(
        "dcmotor",
        {"in1": "5", "in2": "6", "enable": "9"},
        name="drive_motor",
    )

    commands = builder.required_commands(conn)
    handler = builder.build_handler(conn)

    assert [(pin.pin, pin.mode) for pin in builder.pin_modes(conn)] == [
        ("5", PinMode.OUTPUT),
        ("6", PinMode.OUTPUT),
        ("9", PinMode.OUTPUT),
    ]
    assert [command.method for command in commands] == ["WRITE"]
    assert commands[0].params["direction"].enum == ["forward", "reverse", "stop"]
    assert commands[0].params["speed"].type == ParameterType.INT
    assert commands[0].params["speed"].min == 0
    assert commands[0].params["speed"].max == 255
    assert "analogWrite(9, speed);" in handler
    assert "analogWrite(9, 0);" in handler

    conn_without_enable = connection(
        "dcmotor",
        {"in1": "5", "in2": "6"},
        name="drive_motor",
    )
    with pytest.raises(KeyError):
        builder.pin_modes(conn_without_enable)
    with pytest.raises(KeyError):
        builder.build_handler(conn_without_enable)
