from gerbera_sdk import Connection
from gerbera_sdk.contracts.firmware_contract import ColumnType, PinMode
from gerbera_sdk.firmware.configurations import DEVICES_MAPPING
from gerbera_sdk.firmware.devices.ky033 import KY033FirmwareBuilder


def test_ky033_builder_read_contract_without_database() -> None:
    connection = Connection(
        id="line-sensor",
        microcontroller_id="board-1",
        name="line_sensor",
        component_type="ky033",
        pins={"out": "7"},
    )
    builder = KY033FirmwareBuilder()

    pin_modes = builder.pin_modes(connection)
    commands = builder.required_commands(connection)
    schema = builder.required_schema(connection)
    handler = builder.build_handler(connection)

    assert DEVICES_MAPPING["ky033"] is KY033FirmwareBuilder
    assert [(pin.pin, pin.mode) for pin in pin_modes] == [("7", PinMode.INPUT)]
    assert [command.method for command in commands] == ["READ"]
    assert schema["value"].type == ColumnType.INTEGER
    assert builder.build_definitions(connection) == ""
    assert builder.build_stream_lines(connection) == []
    assert "digitalRead(7)" in handler
    assert f"MCP,{connection.event_name},value:" in handler
    assert 'if (action == "WRITE")' not in handler


def test_ky033_builder_stream_contract_with_database() -> None:
    connection = Connection(
        id="line-sensor",
        microcontroller_id="board-1",
        name="line_sensor",
        component_type="ky033",
        pins={"out": "7"},
        database=object(),
    )
    builder = KY033FirmwareBuilder()

    commands = builder.required_commands(connection)
    schema = builder.required_schema(connection)
    definitions = builder.build_definitions(connection)
    stream_lines = "\n".join(builder.build_stream_lines(connection))
    handler = builder.build_handler(connection)

    assert builder.supports_database is True
    assert [command.method for command in commands] == ["READ", "WRITE"]
    assert commands[1].params["state"].enum == ["on", "off"]
    assert schema["id"].primary_key is True
    assert schema["id"].sql_suffix == "GENERATED BY DEFAULT AS IDENTITY"
    assert schema["created_at"].default is None
    assert "bool line_sensor_stream_on = false;" in definitions
    assert f"STREAM,{connection.event_name},value:" in stream_lines
    assert "line_sensor_stream_on = true;" in handler
    assert "line_sensor_stream_on = false;" in handler
