from gerbera_sdk.contracts.command_contract import CommandSpec, ParameterSpec, ParameterType
from gerbera_sdk.contracts.firmware_contract import ColumnSpec, ColumnType
from gerbera_sdk.contracts.firmware_contract import PinMode, PinModeSpec
from gerbera_sdk.firmware.devices.base import BaseFirmwareBuilder
from gerbera_sdk.models.hardware.connection import Connection


class HCSR04FirmwareBuilder(BaseFirmwareBuilder):
    template_name = "hcsr04_read"
    supports_database = True

    def required_libraries(self) -> list:
        return []

    def pin_modes(self, connection: Connection) -> list[PinModeSpec]:
        return [
            PinModeSpec(
                pin=connection.pins["trig"],
                mode=PinMode.OUTPUT,
            ),
            PinModeSpec(
                pin=connection.pins["echo"],
                mode=PinMode.INPUT,
            ),
        ]

    def required_commands(self, connection: Connection) -> list[CommandSpec]:
        commands = [
            CommandSpec(
                method="READ",
                description="Read distance from the HC-SR04 ultrasonic sensor.",
            )
        ]

        if connection.database is None:
            return commands

        commands.append(
            CommandSpec(
                method="WRITE",
                params={
                    "state": ParameterSpec(
                        type=ParameterType.STRING,
                        enum=["on", "off"],
                        description="Turn continuous HC-SR04 stream on or off.",
                    )
                },
                description="Turn continuous HC-SR04 stream on or off.",
            )
        )
        return commands

    def required_schema(self, connection: Connection) -> dict[str, ColumnSpec]:
        _ = connection
        return {
            "id": ColumnSpec(
                type=ColumnType.INTEGER,
                primary_key=True,
                nullable=False,
                sql_suffix="GENERATED BY DEFAULT AS IDENTITY",
            ),
            "distance_cm": ColumnSpec(
                type=ColumnType.FLOAT,
                idx=True,
                nullable=False,
            ),
            "created_at": ColumnSpec(
                type=ColumnType.TIMESTAMP,
                idx=True,
                nullable=False,
            ),
        }

    def build_definitions(self, connection: Connection) -> str:
        if connection.database is None:
            return ""

        return f"bool {connection.name}_stream_on = false;"

    def build_stream_lines(self, connection: Connection) -> list[str]:
        if connection.database is None:
            return []

        read_distance = self._build_distance_read_lines(connection)
        return [
            f"  if ({connection.name}_stream_on) {{",
            *read_distance,
            "    if (duration > 0) {",
            "      float distanceCm = duration * 0.0343 / 2.0;",
            f'      Serial.print("STREAM,{connection.event_name},distance_cm:");',
            "      Serial.println(distanceCm);",
            "    }",
            "    delay(100);",
            "  }",
        ]

    def build_handler(self, connection: Connection) -> str:
        read_distance = "\n".join(self._build_distance_read_lines(connection, indent="  "))

        if connection.database is None:
            return f"""void handle_{connection.name}(const String& input) {{
  (void)input;
{read_distance}
  if (duration == 0) {{
    Serial.println("MCP,{connection.event_name},error:timeout");
    return;
  }}

  float distanceCm = duration * 0.0343 / 2.0;
  Serial.print("MCP,{connection.event_name},distance_cm:");
  Serial.println(distanceCm);
}}"""

        return f"""void handle_{connection.name}(const String& input) {{
  String action = actionOf(input);

  if (action == "WRITE") {{
    String state = parameterValue(input, "state");
    if (state == "on") {{
      {connection.name}_stream_on = true;
      Serial.println("MCP,{connection.event_name},status:on");
      return;
    }}

    if (state == "off") {{
      {connection.name}_stream_on = false;
      Serial.println("MCP,{connection.event_name},status:off");
      return;
    }}

    Serial.println("MCP,{connection.event_name},error:invalid_state");
    return;
  }}

{read_distance}
  if (duration == 0) {{
    Serial.println("MCP,{connection.event_name},error:timeout");
    return;
  }}

  float distanceCm = duration * 0.0343 / 2.0;
  Serial.print("MCP,{connection.event_name},distance_cm:");
  Serial.println(distanceCm);
}}"""

    def _build_distance_read_lines(
        self,
        connection: Connection,
        indent: str = "    ",
    ) -> list[str]:
        trig_pin = connection.pins["trig"]
        echo_pin = connection.pins["echo"]

        return [
            f"{indent}digitalWrite({trig_pin}, LOW);",
            f"{indent}delayMicroseconds(2);",
            f"{indent}digitalWrite({trig_pin}, HIGH);",
            f"{indent}delayMicroseconds(10);",
            f"{indent}digitalWrite({trig_pin}, LOW);",
            f"{indent}long duration = pulseIn({echo_pin}, HIGH, 30000);",
        ]
