from mcp.types import ToolAnnotations

from gerbera_sdk.contracts.command_contract import (
    CommandSpec,
    ParameterSpec,
)
from gerbera_sdk.contracts.firmware_contract import ColumnSpec, ColumnType
from gerbera_sdk.contracts.firmware_contract import PinMode, PinModeSpec
from gerbera_sdk.firmware.devices.base import BaseFirmwareBuilder
from gerbera_sdk.models.hardware.connection import Connection


class HCSR04FirmwareBuilder(BaseFirmwareBuilder):
    supports_streaming = True

    def required_libraries(self) -> list:
        return []

    def pin_modes(self, connection: Connection) -> list[PinModeSpec]:
        return [
            PinModeSpec(
                pin=connection.pins["trig"],
                mode=PinMode.OUTPUT,
            ),
            PinModeSpec(
                pin=connection.pins["echo"],
                mode=PinMode.INPUT,
            ),
        ]

    def required_commands(self, connection: Connection) -> list[CommandSpec]:
        commands = [
            CommandSpec(
                method="READ",
                description="Read distance from the HC-SR04 ultrasonic sensor.",
            )
        ]

        if not connection.stream_enabled:
            return commands

        commands.append(
            CommandSpec(
                method="WRITE",
                params={
                    "state": ParameterSpec(
                        min=0,
                        max=1,
                        description="1 turns continuous HC-SR04 streaming on; 0 turns it off.",
                    )
                },
                description="Set continuous HC-SR04 streaming. Use state 1 for on and 0 for off.",
            )
        )
        return commands

    def annotations(
        self,
        connection: Connection,
        command: CommandSpec,
    ) -> ToolAnnotations:
        method = command.method.strip().upper()
        if method == "READ":
            return ToolAnnotations(
                title=f"Read current distance from {connection.name}",
                readOnlyHint=True,
                destructiveHint=False,
                idempotentHint=True,
                openWorldHint=False,
            )
        if method == "WRITE":
            return ToolAnnotations(
                title=f"Set {connection.name} stream state",
                readOnlyHint=False,
                destructiveHint=False,
                idempotentHint=True,
                openWorldHint=False,
            )
        raise ValueError(f"Unsupported HC-SR04 command: {command.method}")

    def stream_schema(self, connection: Connection) -> dict[str, ColumnSpec]:
        return {
            "id": ColumnSpec(
                type=ColumnType.INTEGER,
                primary_key=True,
                nullable=False,
                sql_suffix="GENERATED BY DEFAULT AS IDENTITY",
            ),
            "distance_cm": ColumnSpec(
                type=ColumnType.FLOAT,
                idx=True,
                nullable=False,
            ),
            "created_at": ColumnSpec(
                type=ColumnType.TIMESTAMP,
                idx=True,
                nullable=False,
            ),
        }

    def build_definitions(self, connection: Connection) -> str:
        if not connection.stream_enabled:
            return ""

        return f"bool {connection.name}_stream_on = false;"

    def build_stream_lines(self, connection: Connection) -> list[str]:
        if not connection.stream_enabled:
            return []

        read_distance = self._build_distance_read_lines(connection)
        return [
            f"  if ({connection.name}_stream_on) {{",
            *read_distance,
            "    if (duration > 0) {",
            "      float distanceCm = duration * 0.0343 / 2.0;",
            f'      Serial.print("STREAM,{connection.event_name},distance_cm:");',
            "      Serial.println(distanceCm);",
            "    }",
            "    delay(100);",
            "  }",
        ]

    def build_handler(self, connection: Connection) -> str:
        read_distance = "\n".join(self._build_distance_read_lines(connection, indent="  "))

        if not connection.stream_enabled:
            return f"""void handle_{connection.name}(const String& input) {{
  (void)input;
{read_distance}
  if (duration == 0) {{
    Serial.println("MCP,{connection.event_name},error:timeout");
    return;
  }}

  float distanceCm = duration * 0.0343 / 2.0;
  Serial.print("MCP,{connection.event_name},distance_cm:");
  Serial.println(distanceCm);
}}"""

        return f"""void handle_{connection.name}(const String& input) {{
  String action = actionOf(input);

  if (action == "WRITE") {{
    String stateValue = parameterValue(input, "state");
    if (stateValue.length() == 0) {{
      Serial.println("MCP,{connection.event_name},error:invalid_arg");
      return;
    }}

    float state = stateValue.toFloat();
    if (state == 1) {{
      {connection.name}_stream_on = true;
      Serial.println("MCP,{connection.event_name},state:1");
      return;
    }}

    if (state == 0) {{
      {connection.name}_stream_on = false;
      Serial.println("MCP,{connection.event_name},state:0");
      return;
    }}

    Serial.println("MCP,{connection.event_name},error:invalid_state");
    return;
  }}

{read_distance}
  if (duration == 0) {{
    Serial.println("MCP,{connection.event_name},error:timeout");
    return;
  }}

  float distanceCm = duration * 0.0343 / 2.0;
  Serial.print("MCP,{connection.event_name},distance_cm:");
  Serial.println(distanceCm);
}}"""

    def _build_distance_read_lines(
        self,
        connection: Connection,
        indent: str = "    ",
    ) -> list[str]:
        trig_pin = connection.pins["trig"]
        echo_pin = connection.pins["echo"]

        return [
            f"{indent}digitalWrite({trig_pin}, LOW);",
            f"{indent}delayMicroseconds(2);",
            f"{indent}digitalWrite({trig_pin}, HIGH);",
            f"{indent}delayMicroseconds(10);",
            f"{indent}digitalWrite({trig_pin}, LOW);",
            f"{indent}long duration = pulseIn({echo_pin}, HIGH, 30000);",
        ]
