from mcp.types import ToolAnnotations

from gerbera_sdk.firmware.firmware_schema import (
    CommandSpec,
    ParameterSpec,
)
from gerbera_sdk.firmware.firmware_schema import (
    ColumnSpec,
    ColumnType,
    PinMode,
    PinModeSpec,
)
from gerbera_sdk.firmware.devices.base import BaseFirmwareBuilder
from gerbera_sdk.models.hardware.connection import Connection


class HW201FirmwareBuilder(BaseFirmwareBuilder):
    supports_streaming = True

    def required_libraries(self) -> list:
        return []

    def pin_modes(self, connection: Connection) -> list[PinModeSpec]:
        return [
            PinModeSpec(
                pin=connection.pins["out"],
                mode=PinMode.INPUT,
            )
        ]

    def required_commands(self, connection: Connection) -> list[CommandSpec]:
        commands = [
            CommandSpec(
                method="READ",
                description="Read the current digital sensor value.",
            )
        ]
        if connection.stream_enabled:
            commands.append(
                CommandSpec(
                    method="WRITE",
                    params={
                        "state": ParameterSpec(
                            min=0,
                            max=1,
                            description="1 turns continuous HW201 streaming on; 0 turns it off.",
                        )
                    },
                    description="Set continuous HW201 streaming. Use state 1 for on and 0 for off.",
                )
            )
        return commands

    def annotations(
        self,
        connection: Connection,
        command: CommandSpec,
    ) -> ToolAnnotations:
        method = command.method.strip().upper()
        if method == "READ":
            return ToolAnnotations(
                title=f"Read current value from {connection.name}",
                readOnlyHint=True,
                destructiveHint=False,
                idempotentHint=True,
                openWorldHint=False,
            )
        if method == "WRITE":
            return ToolAnnotations(
                title=f"Set {connection.name} stream state",
                readOnlyHint=False,
                destructiveHint=False,
                idempotentHint=True,
                openWorldHint=False,
            )
        raise ValueError(f"Unsupported HW201 command: {command.method}")

    def stream_schema(self, connection: Connection) -> dict[str, ColumnSpec]:
        return {
            "id": ColumnSpec(
                type=ColumnType.INTEGER,
                primary_key=True,
                nullable=False,
                sql_suffix="GENERATED BY DEFAULT AS IDENTITY",
            ),
            "value": ColumnSpec(
                type=ColumnType.INTEGER,
                idx=True,
                nullable=False,
            ),
            "created_at": ColumnSpec(
                type=ColumnType.TIMESTAMP,
                idx=True,
                nullable=False,
            ),
        }

    def build_definitions(self, connection: Connection) -> str:
        if not connection.stream_enabled:
            return ""

        return f"bool {connection.name}_stream_on = false;"

    def build_stream_lines(self, connection: Connection) -> list[str]:
        if not connection.stream_enabled:
            return []

        out_pin = connection.pins["out"]
        return [
            f"  if ({connection.name}_stream_on) {{",
            f"    int value = digitalRead({out_pin});",
            f'    Serial.print("STREAM,{connection.event_name},value:");',
            "    Serial.println(value);",
            "    delay(100);",
            "  }",
        ]

    def build_handler(self, connection: Connection) -> str:
        out_pin = connection.pins["out"]

        if not connection.stream_enabled:
            return f"""void handle_{connection.name}(const String& input) {{
  (void)input;
  int value = digitalRead({out_pin});
  Serial.print("MCP,{connection.event_name},value:");
  Serial.println(value);
}}"""

        return f"""void handle_{connection.name}(const String& input) {{
  String action = actionOf(input);

  if (action == "WRITE") {{
    String stateValue = parameterValue(input, "state");
    if (stateValue.length() == 0) {{
      Serial.println("MCP,{connection.event_name},error:invalid_arg");
      return;
    }}

    float state = stateValue.toFloat();
    if (state == 1) {{
      {connection.name}_stream_on = true;
      Serial.println("MCP,{connection.event_name},boolean:1");
      return;
    }}

    if (state == 0) {{
      {connection.name}_stream_on = false;
      Serial.println("MCP,{connection.event_name},boolean:0");
      return;
    }}

    Serial.println("MCP,{connection.event_name},error:invalid_state");
    return;
  }}

  int value = digitalRead({out_pin});
  Serial.print("MCP,{connection.event_name},value:");
  Serial.println(value);
}}"""
