from gerbera_sdk.contracts.command_contract import CommandSpec, ParameterSpec, ParameterType
from gerbera_sdk.contracts.firmware_contract import (
    ColumnSpec,
    ColumnType,
    OutputEventType,
    OutputFieldSpec,
    OutputFieldType,
    PinMode,
    PinModeSpec,
)
from gerbera_sdk.firmware.devices.base import BaseFirmwareBuilder
from gerbera_sdk.models.hardware.connection import Connection


class HW201FirmwareBuilder(BaseFirmwareBuilder):
    template_name = "hw_201_read"
    supports_database = True

    def required_libraries(self) -> list:
        return []

    def pin_modes(self, connection: Connection) -> list[PinModeSpec]:
        return [
            PinModeSpec(
                pin=connection.pins["out"],
                mode=PinMode.INPUT,
            )
        ]

    def required_commands(self, connection: Connection) -> list[CommandSpec]:
        commands = [
            CommandSpec(
                method="READ",
                description="Read the current digital sensor value.",
            )
        ]

        if connection.database is None:
            return commands

        commands.append(
            CommandSpec(
                method="WRITE",
                params={
                    "state": ParameterSpec(
                        type=ParameterType.STRING,
                        enum=["on", "off"],
                        description="Turn continuous HW201 stream on or off.",
                    )
                },
                description="Turn continuous HW201 stream on or off.",
            )
        )
        return commands
    
    def required_schema(self, connection: Connection) -> dict[str, ColumnSpec]:
        return {
            "id": ColumnSpec(
                type=ColumnType.INTEGER,
                primary_key=True,
                nullable=False,
                sql_suffix="GENERATED BY DEFAULT AS IDENTITY",
            ),
            "value": ColumnSpec(
                type=ColumnType.INTEGER,
                idx=True,
                nullable=False,
            ),
            "created_at": ColumnSpec(
                type=ColumnType.TIMESTAMP,
                idx=True,
                nullable=False,
            ),
        }

    def output_contract(
        self,
        connection: Connection,
    ) -> dict[OutputEventType, dict[str, OutputFieldSpec]]:
        outputs: dict[OutputEventType, dict[str, OutputFieldSpec]] = {
            OutputEventType.MCP: {
                "value": OutputFieldSpec(
                    type=OutputFieldType.INTEGER,
                    description="Current digital sensor value.",
                ),
            }
        }

        if connection.database is None:
            return outputs

        outputs[OutputEventType.MCP].update(
            {
                "status": OutputFieldSpec(
                    type=OutputFieldType.TEXT,
                    description="Acknowledged stream state after a WRITE action.",
                ),


                # Might need to delete this later but keeping for now to avoid error handling and unhappy paths, focus on happy path
                "error": OutputFieldSpec(
                    type=OutputFieldType.TEXT,
                    description="Error emitted when a WRITE action is invalid.",
                ),
            }
        )
        outputs[OutputEventType.STREAM] = {
            "value": OutputFieldSpec(
                type=OutputFieldType.INTEGER,
                description="Continuously streamed digital sensor value.",
            ),
        }
        return outputs

    def build_definitions(self, connection: Connection) -> str:
        if connection.database is None:
            return ""

        return f"bool {connection.name}_stream_on = false;"

    def build_stream_lines(self, connection: Connection) -> list[str]:
        if connection.database is None:
            return []

        out_pin = connection.pins["out"]
        return [
            f"  if ({connection.name}_stream_on) {{",
            f"    int value = digitalRead({out_pin});",
            f'    Serial.print("STREAM,{connection.event_name},value:");',
            "    Serial.println(value);",
            "    delay(100);",
            "  }",
        ]
 
    def build_handler(self, connection: Connection) -> str:
        out_pin = connection.pins["out"]

        if connection.database is None:
            return f"""void handle_{connection.name}(const String& input) {{
  (void)input;
  int value = digitalRead({out_pin});
  Serial.print("MCP,{connection.event_name},value:");
  Serial.println(value);
}}"""

        return f"""void handle_{connection.name}(const String& input) {{
  String action = actionOf(input);

  if (action == "WRITE") {{
    String state = parameterValue(input, "state");
    if (state == "on") {{
      {connection.name}_stream_on = true;
      Serial.println("MCP,{connection.event_name},status:on");
      return;
    }}

    if (state == "off") {{
      {connection.name}_stream_on = false;
      Serial.println("MCP,{connection.event_name},status:off");
      return;
    }}

    Serial.println("MCP,{connection.event_name},error:invalid_state");
    return;
  }}

  int value = digitalRead({out_pin});
  Serial.print("MCP,{connection.event_name},value:");
  Serial.println(value);
}}"""
