from gerbera_sdk.contracts.command_contract import CommandSpec, ParameterSpec, ParameterType
from gerbera_sdk.contracts.firmware_contract import ColumnSpec, ColumnType
from gerbera_sdk.contracts.firmware_contract import PinMode, PinModeSpec
from gerbera_sdk.firmware.devices.base import BaseFirmwareBuilder
from gerbera_sdk.models.hardware.connection import Connection


class KY033FirmwareBuilder(BaseFirmwareBuilder):
    template_name = "ky033_read"
    supports_database = True

    def required_libraries(self) -> list:
        return []

    def pin_modes(self, connection: Connection) -> list[PinModeSpec]:
        return [
            PinModeSpec(
                pin=connection.pins["out"],
                mode=PinMode.INPUT,
            )
        ]

    def required_commands(self, connection: Connection) -> list[CommandSpec]:
        commands = [
            CommandSpec(
                method="READ",
                description="Read the current KY-033 line tracking sensor value.",
            )
        ]

        if connection.database is None:
            return commands

        commands.append(
            CommandSpec(
                method="WRITE",
                params={
                    "state": ParameterSpec(
                        type=ParameterType.STRING,
                        enum=["on", "off"],
                        description="Turn continuous KY-033 stream on or off.",
                    )
                },
                description="Turn continuous KY-033 stream on or off.",
            )
        )
        return commands

    def required_schema(self, connection: Connection) -> dict[str, ColumnSpec]:
        return {
            "id": ColumnSpec(
                type=ColumnType.INTEGER,
                primary_key=True,
                nullable=False,
                sql_suffix="GENERATED BY DEFAULT AS IDENTITY",
            ),
            "value": ColumnSpec(
                type=ColumnType.INTEGER,
                idx=True,
                nullable=False,
            ),
            "created_at": ColumnSpec(
                type=ColumnType.TIMESTAMP,
                idx=True,
                nullable=False,
            ),
        }

    def build_definitions(self, connection: Connection) -> str:
        if connection.database is None:
            return ""

        return f"bool {connection.name}_stream_on = false;"

    def build_stream_lines(self, connection: Connection) -> list[str]:
        if connection.database is None:
            return []

        out_pin = connection.pins["out"]
        return [
            f"  if ({connection.name}_stream_on) {{",
            f"    int value = digitalRead({out_pin});",
            f'    Serial.print("STREAM,{connection.event_name},value:");',
            "    Serial.println(value);",
            "    delay(100);",
            "  }",
        ]

    def build_handler(self, connection: Connection) -> str:
        out_pin = connection.pins["out"]

        if connection.database is None:
            return f"""void handle_{connection.name}(const String& input) {{
  (void)input;
  int value = digitalRead({out_pin});
  Serial.print("MCP,{connection.event_name},value:");
  Serial.println(value);
}}"""

        return f"""void handle_{connection.name}(const String& input) {{
  String action = actionOf(input);

  if (action == "WRITE") {{
    String state = parameterValue(input, "state");
    if (state == "on") {{
      {connection.name}_stream_on = true;
      Serial.println("MCP,{connection.event_name},status:on");
      return;
    }}

    if (state == "off") {{
      {connection.name}_stream_on = false;
      Serial.println("MCP,{connection.event_name},status:off");
      return;
    }}

    Serial.println("MCP,{connection.event_name},error:invalid_state");
    return;
  }}

  int value = digitalRead({out_pin});
  Serial.print("MCP,{connection.event_name},value:");
  Serial.println(value);
}}"""
